name: amino_therapy
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  get_it: ^8.0.3
  easy_localization: ^3.0.8
  sizer: ^3.0.3
  http: ^1.2.2
  shared_preferences: ^2.3.2
  file_picker:
  screen_protector: ^1.4.2+1
  flutter_security_checker: ^3.0.0
  go_router: ^16.2.2
  url_launcher: ^6.3.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  internet_connection_checker:

  flutter_bloc: ^8.1.6
  permission_handler: ^11.4.0
  encrypt: ^5.0.3
  flutter_spinkit: ^5.2.1
  cached_network_image: ^3.4.1
  infinite_scroll_pagination: ^4.1.0
  flutter_svg: ^2.0.14
  flutter_dotenv: ^5.2.1
  connectivity_plus:

  # # Firebase
  firebase_core: ^3.15.2
  firebase_analytics: ^11.6.0
  firebase_crashlytics: ^4.3.10
  firebase_messaging: ^15.2.10

  # App update
  in_app_update: ^4.2.5
  in_app_review: ^2.0.11
  upgrader: ^12.1.0
  package_info_plus: ^8.1.2

  # Notifications
  flutter_local_notifications: ^17.1.1

  # Share
  share_plus: ^10.1.2
  local_auth: ^2.3.0
  flutter_slidable: ^3.1.2

  flutter_widget_from_html: ^0.15.3

  flutter_secure_storage: ^9.2.4
  skeletonizer: ^2.1.0+1
  badges: ^3.1.2
  device_info_plus:
  location: ^8.0.0
  animations: ^2.0.11
  image_picker: ^1.1.2
  path: ^1.8.3
  characters: ^1.3.0
  open_filex: ^4.7.0
  device_preview: ^1.3.1
  path_provider: ^2.1.5
  external_path: ^2.2.0
  http_certificate_pinning: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash:
  rename: ^3.1.0

# flutter_launcher_icons:
#   android: true
#   ios: true
#   remove_alpha_ios: true
#   android_flavor: prod
#   iOS_flavor: prod
#   image_path_android: "assets/images/app_icon/app_icon_ios_prod.png"
#   image_path_ios: "assets/images/app_icon/app_icon_ios_prod.png"


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/translations/
    - assets/fonts/
    - assets/images/png/
    - assets/images/svg/
    - api_end_points.env

  fonts:
    - family: IBM_Plex_Sans
      fonts:
        - asset: assets/fonts/IBMPlexSans_Condensed-Light.ttf
          weight: 300
        - asset: assets/fonts/IBMPlexSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSans_Condensed-Regular.ttf
          weight: 500
        - asset: assets/fonts/IBMPlexSans_Condensed-Bold.ttf
          weight: 700
